import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form/Form";
import Header from "../components/Header/Header";
import Wallet from "../components/Wallet/Wallet";
import { DAppProvider, useEthers, Config, Rinkeby } from "@usedapp/core";
import { useEffect, useState } from "react";
import axios from "axios";
import { getDefaultProvider } from "ethers";

const config: Config = {
  readOnlyChainId: Rinkeby.chainId,
  readOnlyUrls: {
    [Rinkeby.chainId]: getDefaultProvider("rinkeby"),
  },
};

const ETH_TO_USD_URL =
  "https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH,MATIC&tsyms=USD";

const Home: NextPage = () => {
  const { active, chainId } = useEthers();
  const [rate, setRate] = useState({
    eth: 0,
    matic: 0,
  });

  const init = async () => {
    const { data } = await axios.get(ETH_TO_USD_URL);
    setRate({
      eth: data.ETH.USD,
      matic: data.MATIC.USD,
    });
  };

  useEffect(() => {
    init();
    return () => {
      setRate({
        eth: 0,
        matic: 0,
      });
    };
  }, [chainId, active]);

  if (
    config &&
    config.readOnlyUrls &&
    chainId &&
    !config.readOnlyUrls[chainId]
  ) {
    return <p>Please use rinkeby testnet.</p>;
  }

  return (
    <DAppProvider config={config}>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Head>
          <title>Buy Me A Coffee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Wallet />
        <Form rate={rate} />
      </div>
    </DAppProvider>
  );
};

export default Home;
