import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form/Form";
import Header from "../components/Header/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Buy Me A Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Form />
    </div>
  );
};

export default Home;
