import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form/Form";
import Header from "../components/Header/Header";
import Wallet from "../components/Wallet/Wallet";

const Home: NextPage = () => {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Head>
        <title>Buy Me A Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Wallet />
      <Form />
    </div>
  );
};

export default Home;
